package com.forgerag.agent;

import java.util.ArrayList;
import java.util.List;

/**
 * Shared state object threaded through every node in the LangGraph4j graph.
 *
 * Design principle: every node reads from and writes to this one object —
 * keeps data flow explicit and testable. See ARCHITECTURE.md.
 *
 * Fields:
 *  - query        the current search query (rewritten by QueryRewriterNode on retry)
 *  - originalQuery the user's original query (never mutated, for context)
 *  - retrievedContext  list of chunk texts returned by RetrievalNode
 *  - draftAnswer  generated by GenerationNode
 *  - verdict      "VALID" | "HALLUCINATED" — set by EvaluationNode
 *  - evaluationReasoning  LLM-judge's explanation
 *  - retryCount   number of rewrite-and-retry cycles executed so far
 *  - maxRetries   cap from application.properties (forgerag.agent.max-retries)
 */
public class AgentState {

    private String query;
    private String originalQuery;
    private List<String> retrievedContext = new ArrayList<>();
    private String draftAnswer;
    private String verdict;
    private String evaluationReasoning;
    private int retryCount = 0;
    private int maxRetries;

    public AgentState() {}

    public AgentState(String query, int maxRetries) {
        this.query = query;
        this.originalQuery = query;
        this.maxRetries = maxRetries;
    }

    // ── Accessors ──────────────────────────────────────────────────────────

    public String getQuery() { return query; }
    public void setQuery(String query) { this.query = query; }

    public String getOriginalQuery() { return originalQuery; }
    public void setOriginalQuery(String originalQuery) { this.originalQuery = originalQuery; }

    public List<String> getRetrievedContext() { return retrievedContext; }
    public void setRetrievedContext(List<String> retrievedContext) { this.retrievedContext = retrievedContext; }

    public String getDraftAnswer() { return draftAnswer; }
    public void setDraftAnswer(String draftAnswer) { this.draftAnswer = draftAnswer; }

    public String getVerdict() { return verdict; }
    public void setVerdict(String verdict) { this.verdict = verdict; }

    public String getEvaluationReasoning() { return evaluationReasoning; }
    public void setEvaluationReasoning(String reason) { this.evaluationReasoning = reason; }

    public int getRetryCount() { return retryCount; }
    public void incrementRetryCount() { this.retryCount++; }

    public int getMaxRetries() { return maxRetries; }
    public void setMaxRetries(int maxRetries) { this.maxRetries = maxRetries; }

    public boolean isRetryLimitReached() { return retryCount >= maxRetries; }

    public boolean isGrounded() { return "VALID".equalsIgnoreCase(verdict); }

    @Override
    public String toString() {
        return "AgentState{query='" + query + "', retryCount=" + retryCount +
               ", verdict='" + verdict + "', grounded=" + isGrounded() + "}";
    }
}
